### ISSUE TITLE
Results.Node property name is unclear

### ISSUE THREAD

**Issue by chriscm2006** [dequelabs/axrl#1]
The word "Node" means something in HTML, but node is meaningless in iOS and misleading in Android... conflicts with AccessibilityNodeInfo, frequently shortened to Node. However, the Node in question and an AccessibilityNodeInfo would not be the same thing. 

Would prefer if we rename this to be more technology agnostic. 

Alternatives: view, control

Priority: moderate

**Comment by WilcoFiers** [comment]
I'm not keen on either the word "view" or "control". When I hear "view" I think MVC, where a view is a stand-alone region of the UI, often the entire UI of an application. A control on the other hand sounds to me like something interactive, that doesn't sound like the right word for it either.

If "node" is an issue, I'd prefer something like "component". Alternatively we could go for something more abstract. In the [ACT Rules Format](https://www.w3.org/TR/act-rules-format/) we used the term "test target", side stepping the question of what the thing is all together. It fits in the theme of "test subject", which is what I've used in place of page / window / tab.

WDYT?

**Comment by WilcoFiers** [comment]
I've decided on "target" as the property, and "TestTarget" as the name for the abstract class. Axe-core already has a "target" property, so it'll seem familiar, it fits with established W3C lingo for this, and it solves this issue raised by Chris.

**Comment by chriscm2006** [comment]
@WilcoFiers This is the best solution for this I've seen. Thanks for putting thought into this!!! @jldailey13 @cyono-deque we should make sure our results structure update to this before we publish 1.0. OR we should announce that our API may change at CSUN and release a 0.#.# version for CSUN.
