### ISSUE TITLE
Results.Node should be a @view (or some other flexible object)

### ISSUE THREAD

**Issue by chriscm2006** [dequelabs/axrl#2]
Selector is a web specific as is the ability to grab "code", which to be honest, even code snippet is misleading here. This is an html tag. Regardless, both Selector and CodeSnippet are impossible in mobile.

I think the best solution for this is to use the @view solution you've used prior. `results[0].@view` and allow the contents of @view to be defined by the type. Or perhaps, that's already the way it works and I'm misunderstanding?

Priority: high

**Comment by WilcoFiers** [comment]
Hey Chris. Here's some new iOS example snippet. I spoke to Jennifer about this yesterday. I think this does what you need it to, can you confirm?

```json
{
  "@type": "TestSuccess",
  "helpUrl": "https://dequeuniversity.com/rules/axe-ios/1.0/color-contrast",
  "node": {
    "@type": "UIView",
    "className": "UILabel",
    "frame": "(107.5, 156.5, 106.0, 20.5)",
    "visibleLabel": "Gray on Black",
    "identifier": "DequeAddedID_11"
  }
}
```
