### ISSUE TITLE
Remediation Advice should not be required

### ISSUE THREAD

**Issue by chriscm2006** [dequelabs/axrl#3]
Remediation advice should not be a required property. In fact, in the example you gave, the remediation advice already feels like secondary information:

```
"description": "Web pages must have a title",

"remediation": "Add a title to the web page",
```

**Comment by WilcoFiers** [comment]
Thanks for reporting. This wasn't stated explicitly, but the only required property is `@type`. All other properties are optional. I'm adding in a "requirements" section to explain this, and the few other requirements that there are.
